README.md

After switching testing frameworks from Mocha to Jest, I wanted a similar way to view and filter test results within an HTML file.  Existing Jest HTML results processors work fine but do not show a modern looking UI and cannot filter on "pass" or "fail" tests.
[jest-stare](https://github.com/dkelosky/jest-stare) is a Jest "results processor" is an attempt to recreate a [mochawesome](https://github.com/adamgruber/mochawesome) like report for Jest.

jest-stare Results Processor

---

README.md

[jest-img-snapshot](https://github.com/donysukardi/jest-img-snapshot) is an alternative to [americanexpress/jest-image-snapshot](https://github.com/americanexpress/jest-image-snapshot) with all the Jest's snapshot goodies out of the box.
It works slightly differently from `jest-image-snapshot` in the way that it leverages on Jest's `toMatchSnapshot` on top of generating image artefacts. That way, you get to update failing snapshot and have access to obsolete snapshots.
It currently monkey patches into Jest's snapshotState to remove artefacts from obsolete snapshots.

Add jest-img-snapshot

---

README.md

It seems like results processors are being deprecated and "jest-stare" handles being run as a reporter, so I'd like to move the reference to this project under the non-deprecated term.

Move jest-stare to Reporter Instead of Results Processor

---

README.md

No dependencies, no interactive shell needed.  Prints out the slowest 10 tests in your app.  Can also print warnings when a test exceeds X ms.

adding jest-slow-test-reporter

---

README.md

[jest-shell-matchers](https://github.com/raingerber/jest-shell-matchers) adds support for unit testing shell scripts, while also using Jest to mock specific commands. For example, you could mock ```curl``` to prevent network requests. Like any mock, you can also define the output and make assertions about the input.

Add jest-shell-matchers

---

README.md

This PR adds a link to the `eslint-plugin-jest-formatting` repo.
This project aims to provide formatting rules (auto-fixable where possible) to ensure consistency and readability in jest test suites.

Added a link to `eslint-plugin-jest-formatting`

---

README.md

Add reporter: jest-standard-reporter
Replaces the default reporter that uses stderr for printing messages, this breaks build agents that are Windows OS.

Adding jest-standard-reporter

---

README.md

[`node-recorder`](https://github.com/ericclemmons/node-recorder/#using-jest) has a Jest watch plugin that toggles recording modes:
> ![](https://raw.githubusercontent.com/ericclemmons/node-recorder/master/demo.gif)

Add reference to node-recorder's watch plugin

---

README.md

Hello,
I wrote [this jest plugin](https://github.com/ballercat/jest-plugin-must-assert) to help catch runtime issues in Jest tests. My team and I found it to be very useful in catching poor test logic via runtime assertions. I'd like to add it to this list to help others in a similar situation.
Also fixed a couple of small typos while at it.

Add jest-plugin-must-assert

---

README.md

- [jest-less-loader](https://github.com/hustcc/jest-less-loader) Jest transformer for `.less` file.
- [jest-url-loader](https://github.com/hustcc/jest-url-loader) Similar with webpack's `url-loader` for Jest transformer.

feat: add url-loader, less-loader

---

README.md

**jest-runner-groups** is a custom runner that allows engineers to tag tests and execute groups of tests.
Repo: https://github.com/eugene-manuilov/jest-runner-groups

Add jest-runner-groups

---

README.md

[jest-it-up](https://github.com/rbardini/jest-it-up) ensures incremental coverage gains are not lost by automatically bumping up global Jest thresholds whenever coverage goes above them.
I've added it under a new _Coverage_ category before _Snapshot_, as I didn't find an appropriate category for this package, but let me know if you have a better suggestion.

Add jest-it-up

---

README.md

[`jest-openapi`](https://github.com/RuntimeTools/OpenAPIValidators/tree/master/packages/jest-openapi) lets you automatically test whether your server's behaviour and documentation match. It adds Jest matchers that support the [OpenAPI standard](https://swagger.io/docs/specification/about/) for documenting REST APIs. You can simply assert `expect(responseObject).toSatisfyApiSpec()`

Add jest-openapi

---

README.md

[jest-os-detection](https://github.com/doctolib/jest-os-detection) allows to merge the test suites you use on various platforms. For instance:
```js
describe.onWindows('would be skipped on anything different than Windows', () => {})
it.onLinux.each([])('Every test would only run on Linux', () => {})
```

Add jest-os-detection

---

README.md

Added [jest-runner-tsc](https://github.com/azz/jest-runner-tsc). It is listed on Jest's site as an [available runner](https://github.com/azz/jest-runner-tsc).

Added jest-runner-tsc to "runners" section on README

---

README.md

The documentation site to @bigtest/interactor changed recently. This updates the link to the new site.

Fix link to @bigtest/interactor

---

README.md

This Reporter uses versions by TestRail Milestone and adds test results to test Runs that already exist in TestRail, and does not create new ones each time Jest runs, like other Jest to TestRail packages

Add reporter testrail-jest-reporter

---

README.md

I maintain [jest-openapi](https://github.com/openapi-library/OpenAPIValidators/tree/master/packages/jest-openapi) and have migrated it to a new GitHub organisation
Thanks!

Update GitHub link for jest-openapi

---

README.md

Hi,
I have created `jest-coverage-thresholds-bumper` package for my team some time ago to make sure that code coverage never goes down without people looking into it. It is similar to `jest-it-up` package (it looks like both packages were developed at the same time), but it has extra features that `jest-it-up` is missing.

Added jest-coverage-thresholds-bumper under "coverage" category

---

README.md

It may look similar to [jest-json-matcher](https://github.com/americanexpress/jest-json-schema), but jest-json matchers make assertions on the contents of a JSON string; jest-json-matchers asserts that a JS object is of a given schema.

Add jest-json

---

README.md

Some quick clean up. Minor changes:
- always full stop at the end
- no trailing slash in hyper links
- `www.github.com` > `github.com`
- and a couple of links got updated

chore: quick clean up

---

README.md

When debugging a Jest test (e.g: React), it's extremely difficult to imagine what the UI looks like in your head. [jest-preview](https://github.com/nvh95/jest-preview) helps to preview the UI of your app in Jest to an external browser (such as Chrome), increasing productivity when debugging or writing new tests.
https://stackblitz.com/edit/jest-preview?file=README.md
https://github.com/nvh95/jest-preview
https://www.jest-preview.com/docs/getting-started/intro

Add `jest-preview`

---

README.md

Added [@putout/plugin-jest](https://github.com/coderaiser/putout/blob/master/packages/plugin-jest/README.md) that contains rules to migrate to latest Jest API.

docs: add @putout/plugin-jest

---

README.md

Adds the `jest-a-coverage-slip-detector` package to the Coverage category. One of the unique capabilities from the other two in that category is that it supports parallelized CI runs, with automatic merging of coverage.

Add jest-a-coverage-slip-detector

---

README.md

Rename `@testing-library/jest-dom` and `@emotion/jest` (and fix broken links).

Rename `@testing-library/jest-dom` and `@emotion/jest`

---

README.md

Add the github-actions-jest-reporter package. This package emulates jest default one but uses Github Actions groups for logging, thus folding passed test and leaving failed ones spread out to show at first glance what went wrong but preserving all the details.

Add github-actions-jest-reporter package

---

README.md

Added the Jest CI spec reporter. A zero-dependency reporter which outputs using the same design principals as the popular karma-spec-reporter, producing clean text-based and easily searchable results in console logs.

Add jest-ci-spec-reporter to the list

---

README.md

Given a failing test that is marked with `it.failing`, the standard Jest reporters will report such a test in exactly the same way as if it were passing. This can make it difficult to see at a glance which tests still need work.
Instead, the `jest-wip-reporter` classifies any `.failing`, `.skip` or `.todo` test as "work in progress", clearly reporting that such tests are not yet completely developed. At the end of the test run the reporter provides a list of those tests that are still work-in-progress.

Add jest-wip-reporter to the README's list of reporters

---

README.md

`@tsdoc-test-reporter/jest` is a test reporter that attaches JS/TSDoc comments to your test results. It is mainly used to generate a summary in HTML but can also output JSON. Enabling you to add metadata to your test results.
Reporter:
https://github.com/tsdoc-test-reporter/reporter
Example output:
https://tsdoc-test-reporter.github.io/kitchen-sink/

add `@tsdoc-test-reporter/jest` to list of reporters

---

README.md

Hey,
here is a link to my vscode extension: [vscode-jest-runner](https://github.com/firsttris/vscode-jest-runner) 
[vscode-jest-runner](https://github.com/firsttris/vscode-jest-runner)  offers a simple way to run or debug one or more tests from context menu, codelens or command plalette.
While [vscode-jest](https://github.com/jest-community/vscode-jest) is running your current test-suite everytime you change it, [vscode-jest-runner](https://github.com/firsttris/vscode-jest-runner) is focused on running or debugging a specific test or test-suite.
Recently vscode-jest-runner reached over 1M  installs on [Visual-Studio-Marketplace](https://marketplace.visualstudio.com/items?itemName=firsttris.vscode-jest-runner).
[Since 2020](https://github.com/nrwl/nx/issues/3868) vscode-jest-runner will be …

add link to vscode-jest-runner to README

---

README.md

`@geek-fun/jest-search` is a Presets like `jest-elasticsearch`, but it also enable the support for OpenSearch and ZincSearch, it also support specify the version of search eingine in config file rather than folk and build its own package,
and more it also export functions to start and stop engine so user can not only setup environment through Presets globally but also can make it run in specific test only
jest-search:
https://github.com/geek-fun/jest-search

add `@geek-fun/jest-search` to list of Presets

---

README.md

A Jest reporter designed to enhance readability and organization of console messages. It automatically groups console messages, reducing clutter and making it easier to interpret large volumes of output. Additionally, it integrates seamlessly with GitHub Actions, ensuring clean and concise message display. This reporter is particularly useful for projects with extensive console messages, as it turns repetitive console messages into a neatly structured overview.

feat: add jest-console-group-reporter to reporter list
