- README.md
I hope that's the right place to mention the project.
> Add jest-webdriver project

- README.md
https://github.com/sapegin/jest-cheat-sheet
> Add Jest cheat sheet

- README.md
Add link to https://github.com/macku/jest-puppe-shots
> Add `jest-puppe-shots` extension

- README.md
I have taken @orta's quote from Twitter as a description :)
> Add wallaby

- README.md
I want this to fit better with wallaby in the set now
> Update README.md for vscode-jest

- README.md
I wasn't sure which category to place under, do you guys think `Library extensions` is the right one?
> Add babel-jest-assertions

- README.md
Not sure about the category or description...
> add jest-fetch-mock

- README.md
- expect-puppeteer
- jest-environment-puppeteer
- jest-puppeteer (preset)
Following https://github.com/facebook/jest/pull/5722
> Add Jest Puppeteer

- README.md
Add:
- [jest-enzyme](https://github.com/FormidableLabs/enzyme-matchers/tree/master/packages/jest-enzyme)
- [enzyme-to-json](https://github.com/adriantoine/enzyme-to-json)
- [React Jest workshop](https://github.com/kentcdodds/react-jest-workshop).
- [jest-styled-components](https://github.com/styled-components/jest-styled-components)
I wasn't sure which categories the following should go under?
- [vue-jest](https://github.com/vuejs/vue-jest)
- [storyshots](https://github.com/storybooks/storybook/tree/master/addons/storyshots)
> Add popular packages/resources

- README.md
I was impressed by @asvetliakov's work on using the typescript dev server to provide deeper jest integration 👍
> Add typescript-snapshots-plugin

- README.md
> Add jest-electron-runner

- README.md
How did we forget this one 😱 
/cc @Raathigesh
> Add Majestic

- README.md
Adding Differencify as a visuall regression testing tool which uses Jest to run and has
- Pupeteer integrated
- Supports commands chaining
- CI friendly
- Freeze Images
> Add Differencify

- README.md
jest-generator allows to test generator function easily
> Add jest-generator matcher

- README.md
JUnit and xUnit are awesome test report formats for CI/CD systems. The projects added in this PR are awesome for allowing Jest to integrate with existing CI/CD systems such as Azure DevOps, Jenkins, etc.
> added additional reporters

- README.md
this is definitely somewhat duplicative of the silent reporter package with the use dots flag, but i think the differences in these packages makes this worthwhile
> adding a simple dot reporter

- README.md
> Add @bigtest/interactor to Library extensions

- README.md
> Add StoryShots link

- README.md
[Allure Framework](https://github.com/allure-framework/allure2) is a flexible lightweight multi-language test report tool that not only
shows a very concise representation of what has been tested in a neat web report form,
but allows everyone participating in the development process to extract the maximum of useful
information from everyday execution of tests.
> Add jest-allure

- README.md
Was suggested to me to add this package to the list https://github.com/facebook/jest/issues/8551#issuecomment-502337021
> Add jest-large-snapshot-warning

- README.md
> add jest-watch-continue and jest-watch-random

- README.md
> Create presets section.

- README.md
👋🏻 
Add [jest-wake-lock-mock](https://github.com/jorisre/jest-wake-lock-mock) in the mock section
> Add jest-wake-lock-mock

- README.md
`jest-each` has been merged into the core Jest repo (congrats!)
> Removed jest-each

- README.md
**jest-preset-angular** is a preset of Jest configuration for Angular projects.
Repo: https://github.com/thymikee/jest-preset-angular
> Add jest-preset-angular

- README.md
https://github.com/magicmark/jest-how-do-i-mock-x shows runnable examples for common testing situations that often prove challenging
> Add Jest: How do I mock x?

- README.md
Adding a new category `generators` as none of the existing categories are fitting
> Add `jest-test-gen` scaffold generator

- README.md
Inspired by latest Jest blog post – would be nice to add `jest-runner-tsd` and `jest-light-runner` here too.
Also fixed a typo and run Prettier.
> Add `jest-runner-tsd` and `jest-light-runner`

- .github/workflows/prettier.yml
- package.json
Ah.. Prettier was running. Lat’s fix. Just could not see it yesterday.
> Fix prettier script name

- README.md
Let’s add `jest-serializer-ansi-escapes` to the list? (;
> Add `jest-serializer-ansi-escapes`

- README.md
Added the jest-tesults-reporter package to the reporters list.
> Added jest-tesults-reporter to list.

- README.md
List `jest-native` matchers package.
> Add `jest-native`

- README.md
Add `eslint-plugin-jest-extended` and `eslint-plugin-jest-dom` the Linting list.
> Add `eslint-plugin-jest-extended` and `eslint-plugin-jest-dom`

- README.md
Suggestion to add [@jest-mock/express](https://github.com/bikk-uk/jest-mock-express) to the mocks section.
> Add `@jest-mock/express`

- README.md
Suggestion to add [@automock/jest](https://github.com/omermorad/automock)
> Add `@automock/jest`

- README.md
A made a little tool which makes my life easier. https://github.com/thymikee kindly suggested I added a link to it here. Happy to change any part of my PR. Thanks for reading.
> Added link to www.text2jest.com in the "Generators" section

- README.md
Added the reporter `jest-ado-reporter` for Azure DevOps.
> Add `jest-ado-reporter` for Azure DevOps

- README.md
Adds [`jest-fail-on-console`](https://github.com/ValentinH/jest-fail-on-console) utility.
Thanks for making it @ValentinH. Very useful!
> Add `jest-fail-on-console`
